# Generated by Django 6.0.6 on 2026-06-09 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acteurs',
            fields=[
                ('idacteurs', models.AutoField(primary_key=True, serialize=False)),
                ('nomAct', models.CharField(max_length=45)),
                ('prenomAct', models.CharField(max_length=45)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='acteurs/')),
            ],
            options={
                'verbose_name_plural': 'Acteurs',
                'db_table': 'acteurs',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('idcategories', models.AutoField(primary_key=True, serialize=False)),
                ('nomCat', models.CharField(max_length=100)),
                ('descriptif', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Personnes',
            fields=[
                ('idpersonnes', models.AutoField(primary_key=True, serialize=False)),
                ('pseudo', models.CharField(max_length=45, unique=True)),
                ('nomPer', models.CharField(max_length=45)),
                ('prenomPer', models.CharField(max_length=45)),
                ('mail', models.EmailField(max_length=100, unique=True)),
                ('mot_de_passe', models.CharField(max_length=25)),
                ('type', models.CharField(choices=[('professionnel', 'Professionnel'), ('amateur', 'Amateur')], max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Personnes',
                'db_table': 'personnes',
            },
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('idfilms', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=45)),
                ('anneesortie', models.IntegerField()),
                ('affiche', models.ImageField(upload_to='affiches/')),
                ('realisateur', models.CharField(max_length=45)),
                ('acteurs', models.CharField(max_length=45)),
                ('idcategorie', models.ForeignKey(blank=True, db_column='idcategorie', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seefilm.categories')),
            ],
            options={
                'verbose_name_plural': 'Films',
                'db_table': 'films',
            },
        ),
        migrations.CreateModel(
            name='Commentaires',
            fields=[
                ('idcommentaires', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField()),
                ('dateCom', models.DateTimeField()),
                ('idfilmsC', models.ForeignKey(db_column='idfilmsC', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seefilm.films')),
                ('idpersonnesC', models.ForeignKey(db_column='idpersonnesC', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seefilm.personnes')),
            ],
            options={
                'verbose_name_plural': 'Commentaires',
                'db_table': 'commentaires',
            },
        ),
        migrations.CreateModel(
            name='FilmsActeurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idacteurs', models.ForeignKey(db_column='idacteurs', on_delete=django.db.models.deletion.PROTECT, to='seefilm.acteurs')),
                ('idfilms', models.ForeignKey(db_column='idfilms', on_delete=django.db.models.deletion.PROTECT, to='seefilm.films')),
            ],
            options={
                'verbose_name_plural': 'Films Acteurs',
                'db_table': 'films_acteurs',
                'unique_together': {('idfilms', 'idacteurs')},
            },
        ),
    ]
