# Generated by Django 6.0.6 on 2026-06-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seefilm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='acteurs',
        ),
        migrations.AlterField(
            model_name='films',
            name='affiche',
            field=models.ImageField(blank=True, null=True, upload_to='affiches/'),
        ),
        migrations.DeleteModel(
            name='FilmsActeurs',
        ),
        migrations.AddField(
            model_name='films',
            name='acteurs',
            field=models.ManyToManyField(blank=True, to='seefilm.acteurs'),
        ),
    ]
